/* 
 *  SAESE Library     
 *  
 *  Email: vbogado@santafe-conicet.gov.ar
 *  Date : 2012
 *  Extended from DEVSSuite Libraries, which can 
 *  be found at http://acims.asu.edu/software/devs-suite
 *  
 */

package SimEnvironment;

import java.awt.Dimension;
import java.awt.Point;
import GenCol.entity;
import SimEnvironment.EFLibrary.SAEExperimentalFrame;
import SimEnvironment.SAModel.SystemTemp.SAViewDEVS;
import view.modeling.ViewableComponent;
import view.modeling.ViewableDigraph;


public class SimEnvironment extends ViewableDigraph{
	//constructors:
	  public SimEnvironment(){
		  this("SimEnvironment");
	  }
	   
	  public SimEnvironment(String name){
		  super(name);
	      saeSimEnvironmentConstruct();
	  }
	  
	  //defining the coupled model
	  public void saeSimEnvironmentConstruct(){
		//input ports
		//start input port
		addInport("sip");
		 
		//adding output ports
		addOutport("esop");
		  
		//metrics:
		addOutport("staop");
		addOutport("sthop");
		addOutport("sfailsop");
		addOutport("savailop");
		addOutport("sunavailop");
		
		//Creating components
		SAViewDEVS saview = new SAViewDEVS("SAView");
		ViewableDigraph ef = new SAEExperimentalFrame("SAE-EF", 21.6, 7776); //name, interarrtime, simtime
				
		//defining the components of this model
		add(saview); //simview of the SA
		add(ef);  //experimental frame for the SAE
		  
		//initialize variables
		initialize();
				  
		//Specifying the couplings:  
		//external input coupling
		addCoupling(this,"sip",ef,"sip");
		  
		//external output coupling
		addCoupling(ef,"staop",this,"staop");
		addCoupling(ef,"sthop",this,"sthop");
		addCoupling(ef,"sfailsop",this,"sfailsop");
		addCoupling(ef,"savailop",this,"savailop");
		addCoupling(ef,"sunavailop",this,"sunavailop");
		 
		//external port: processed request
		addCoupling(saview,"esop",this,"esop");
		 
		//internal coupling
		addCoupling(ef,"rop",saview,"erip");
		
		addCoupling(saview,"esop",ef,"procreqip");
		addCoupling(saview,"rtaop",ef,"rtaip");
		addCoupling(saview,"rdtop",ef,"rdowntimeip");
		addCoupling(saview,"rrtop",ef,"rrecovtimeip");
		addCoupling(saview,"rfailop",ef,"rfailip");
		
		//testing the input ports
		addTestInput("sip",new entity("start"));
		
	}
	    
    /**
     * Automatically generated by the SimView program.
     * Do not edit this manually, as such changes will get overwritten.
     */
    public void layoutForSimView()
    {
        preferredSize = new Dimension(1887, 1152);
        ((ViewableComponent)withName("SAE-EF")).setPreferredLocation(new Point(16, 11));
        ((ViewableComponent)withName("LM System-SAView")).setPreferredLocation(new Point(1, 216));
    }
}
